### ISSUE TITLE
Failing to initialise ruby-julia

### ISSUE THREAD

**Issue by trapeze-bell-peter** [mrkn/ruby-julia#6]
I am trying to use your library to call Julia from Ruby but am failing at the first hurdle.  I have Julia installed in `/usr/local/julia-1.1.0`.  My test code is:

```ruby
Julia.init('/usr/local/julia-1.1.0/bin/julia')
Julia.eval('print(pi)')
```
This is failing at:
```
LoadError:
       cannot load such file -- julia.so
     # /home/peter/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:33:in `require'
     # /home/peter/.rvm/gems/ruby-2.6.1/gems/julia-0.2.0/lib/julia/init.rb:43:in `rescue in init'
     # /home/peter/.rvm/gems/ruby-2.6.1/gems/julia-0.2.0/lib/julia/init.rb:39:in `init'
     # ./spec/models/heathrow_coords_spec.rb:9:in `block (2 levels) in <top (required)>'
```
Looking at the source code, init.rb:43 is executing require `julia.so` but this does not exist in the Gem file.  Is there an installation step I need to do to generate a `julia.so.rb` file.

Many thanks in advance.

Peter.

**Comment by mrkn** [comment]
Thank you for having interest in this project.

I found a bug in gemspec file, fixed it, and release a new experimental version.

Please the new version by `gem install --pre julia`, and try it again.

**Comment by trapeze-bell-peter** [comment]
Thank you for the amazingly speedy turn-around.  That has fixed the issue.
