### ISSUE TITLE
Feature Request: map between Julia tuples and structs and Ruby arrays and hashes

### ISSUE THREAD

**Issue by trapeze-bell-peter** [mrkn/ruby-julia#7]
It is possible, I have missed how to do this.  So apologies in advance if that is the case.
From looking at the source code, it looks like ruby-julia basically only converts primitive types.  The Julia function I have written, and am calling from Ruby returns a Tuple consisting of boolean and a float.
My solution so far, is to write in the Julia world the results tuple into two independent variable, and then do Julia.eval on each variable to receive the the correct values.
I would love it, if Tuples were converted into arrays.  I would also love it, if structs were mapped onto Hash tables.

**Comment by mrkn** [comment]
At first, thank you for having interest in ruby-julia.

ruby-julia is very experimental version. You know, it now supports only eval and conversion of primitive types.

Now I'm working on implementing the system to wrap Julia object in the Ruby side.
Please wait until it is finished.

**Comment by trapeze-bell-peter** [comment]
Many thanks, and I wish you luck.  I would be happy to help to test the feature once you are a bit further.
